---
{{- with .Values.secrets.env.admin }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kc.fullname" $ }}-admin-env
type: Opaque
stringData:
{{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
---
{{- with .Values.secrets.env.db }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kc.fullname" $ }}-db-env
type: Opaque
stringData:
{{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
---
{{- if .Values.db.ssl.enabled }}
{{- with .Values.secrets.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kc.fullname" $ }}-db-ssl-ca
type: Opaque
stringData:
  {{ $.Values.db.ssl.caSecretKey }}: |-
{{ .dbCa | indent 4 }}
{{- end }}
{{- end }}
