---
{{- with .Values.app.secrets.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-env
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
{{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
---
{{- with .Values.app.secrets.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-certificates
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
{{- range . }}
  {{ .fileName }}: |-
{{ .cert | nindent 4 }}
{{- end }}
{{- end }}
