apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commonlib.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-headless
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  selector:
    matchLabels:
      {{- include "commonlib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "commonlib.labels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        prometheus.io/scrape: {{ .Values.annotations.statefulset.prometheus.scrape | quote }}
        prometheus.io/path: {{ .Values.annotations.statefulset.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.annotations.statefulset.prometheus.port | quote }}
    spec:
      serviceAccount: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      affinity:
        {{- include "commonlib.podAntiAffinity" . | nindent 8 }}
      securityContext:
        {{- include "commonlib.podSecurityContext" . | nindent 8 }}
      containers:
        - name: keycloak
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}@{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-{{ .Values.service.port }}
              containerPort: {{ .Values.service.port }}
            - name: http-{{ .Values.service.managementPort }}
              containerPort: {{ .Values.service.managementPort }}
          env:
            {{- include "commonlib.envFromValues" . | nindent 12 }}
            {{- include "commonlib.envFromSecrets" . | nindent 12 }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JAVA_OPTS_APPEND
              value: '-Djgroups.bind.address=$(POD_IP)'
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.managementPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.managementPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- include "commonlib.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            {{- include "commonlib.volumeMounts" . | nindent 12 }}
            - name: keycloak
              mountPath: /opt/keycloak/data
            {{- $mountDir := .Values.app.secrets.certificatesMountDir }}
            {{- range .Values.app.secrets.certificates }}
            - name: certificates
              mountPath: {{ printf "%s/%s" $mountDir .fileName }}
              subPath: {{ .fileName }}
              readOnly: true
            {{- end }}
      volumes:
        {{- include "commonlib.volumes" . | nindent 8 }}
        - name: keycloak
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
        {{- with .Values.app.secrets.certificates }}
        - name: certificates
          secret:
            secretName: {{ $.Release.Name }}-certificates
        {{- end }}
